apiVersion: apps/v1
kind: Deployment
metadata:
  name: gis-test
  namespace: dev
  labels:
    app: gis-test
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gis-test
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: gis-test
        version: v1
    spec:
      # nodeSelector:
      #   env: dev
      containers:
        - name: gis-test
          image: "asia.gcr.io/trav-project/gis-test:dev"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 400Mi
          ports:
            - name: http
              containerPort: 3000
          